### ISSUE TITLE
White text on white background on Mac OS X

### ISSUE THREAD

**Issue by zamoose** [Brilleslange/tica#1]
Howdy! Running `python3 tica.py` from a venv virtual environment (Python 3.7.4) results in a blank screen similar to the following:

![Screen Shot 2019-10-18 at 10 06 24 AM](https://user-images.githubusercontent.com/862531/67101161-1b2c0d80-f18f-11e9-9ea0-aa1b9af19676.png)

The UI all appears to be functional (I can click the checkboxes and get results, for instance) but just not visible:

![Screen Shot 2019-10-18 at 10 10 23 AM](https://user-images.githubusercontent.com/862531/67101389-8b3a9380-f18f-11e9-8395-2c4ea5074692.png)

Thanks!

**Comment by zamoose** [comment]
Update: Mac info.

![Screen Shot 2019-10-18 at 10 11 18 AM](https://user-images.githubusercontent.com/862531/67101458-a907f880-f18f-11e9-81e9-20449511f01d.png)

**Comment by Brilleslange** [comment]
I've pushed a new version to the macfix branch, could you check if that works?

**Comment by zamoose** [comment]
Looks good!

![Screen Shot 2019-10-25 at 2 13 37 PM](https://user-images.githubusercontent.com/862531/67598778-6b314400-f73c-11e9-909a-90d38c5b5e44.png)

**Comment by Brilleslange** [comment]
Okay, great! Apparently the cause of it is that Mac OS X's dark mode turns the text white. The program now uses a different set of widgets in the GUI if the user is on a Mac OS.
